/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import custom.HDBanhang;
import custom.HDCTBanHang;
import custom.HDCTBanHangCustom;
import entity.HoaDon;
import entity.KhuyenMai;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import service.impl.HoaDonChiTietServiceImpl;
import service.impl.HoaDonServiceImpl;
import service.impl.KhuyenMaiServiceImpl;
import util.UserHelper;
import static view.DLThanhToan.cm_to_pp;

/**
 *
 * @author admin
 */
public class ChiTietHoaDonJdialog extends javax.swing.JDialog {

    private DefaultTableModel model;
    private HoaDonServiceImpl service;
    private KhuyenMaiServiceImpl kmservice;
    private HoaDonChiTietServiceImpl serviceHdct;
    private List<HDBanhang> listsHD;
    private List<HDCTBanHang> listsHDCT;
    List<HDCTBanHangCustom> dsmon;
    KhuyenMai km ;
     HoaDon hoadon;
     Double btHeight = 0.0;
    Double bbHeight = 0.0; 
      ArrayList<String> tenMon = new ArrayList<>();
    ArrayList<Integer> soLuongMon = new ArrayList<>();
    ArrayList<BigDecimal> donGiaMon = new ArrayList<>();
    //ArrayList<BigDecimal> thanhTienMon = new ArrayList<>();
    
    public ChiTietHoaDonJdialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        service = new HoaDonServiceImpl();
        serviceHdct = new HoaDonChiTietServiceImpl();
        kmservice = new KhuyenMaiServiceImpl();
        listsHD = service.getListHDCustom(UserHelper.ma);
        listsHDCT = serviceHdct.getHDCTByHD(UserHelper.ma);
        loadForm(listsHD);
        
        loadDataToTable(listsHDCT);
        setFormHD();
    }

    private void loadDataToTable(List<HDCTBanHang> listsHDCT) {
        model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0);
        int stt = 1;
        for (HDCTBanHang hDCTBanHang : listsHDCT) {
            model.addRow(new Object[]{stt++, hDCTBanHang.getMaMon(), hDCTBanHang.getTenMon(),
                hDCTBanHang.getGiaTien(), hDCTBanHang.getSoLuong()});
        }
    }

    private double getTongTien() {
        
        
        listsHDCT = serviceHdct.getHDCTByHD(UserHelper.ma);
        double tongTien = 0;
        for (HDCTBanHang hDCTBanHang : listsHDCT) {
            tongTien += hDCTBanHang.getGiaTien().doubleValue() * hDCTBanHang.getSoLuong();
        }
        return tongTien;
    }

    private void loadForm(List<HDBanhang> listsHD) {
        //km = kmservice.getbyMaKM(lblGiamGia.getText());
        HDBanhang hoaDon = listsHD.get(0);
        lblBan.setText(hoaDon.getMaBan());
        lblGiamGia.setText(hoaDon.getMaKM());
        lblKhuVuc.setText(hoaDon.getMaKV());
        lblMa.setText(hoaDon.getMaHD());
        lblNgayTao.setText(String.valueOf(hoaDon.getNgayTao()));
        lblThanhTien.setText(String.valueOf(this.getTongTien()));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNgayTao = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblKhuVuc = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblThanhTien = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblGiamGia = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnInHD = new javax.swing.JButton();
        lblMa = new javax.swing.JLabel();
        lblBan = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNgayTao.setText("jLabel3");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Chi Tiết Hóa Đơn");

        lblKhuVuc.setText("jLabel3");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mã Hoá đơn:");

        lblThanhTien.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Số bàn:");

        lblGiamGia.setText("jLabel3");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Ngày tạo:");

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã sp", "Tên sp", "Giá tiền", "Số lượng"
            }
        ));
        jScrollPane1.setViewportView(tblSanPham);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Khu Vực:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Giảm giá:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Thành tiền:");

        btnInHD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInHD.setIcon(new javax.swing.ImageIcon("C:\\Test\\QLNhaHang\\src\\main\\java\\image\\inhoadon.png")); // NOI18N
        btnInHD.setText("In hoá đơn");
        btnInHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInHDActionPerformed(evt);
            }
        });

        lblMa.setText("jLabel3");

        lblBan.setText("jLabel3");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Test\\QLNhaHang\\src\\main\\java\\image\\huymon.png")); // NOI18N
        jButton1.setText("Huỷ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMa, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblThanhTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNgayTao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblKhuVuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGiamGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnInHD)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(320, 320, 320))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblMa))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblBan))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblNgayTao))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblKhuVuc))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGiamGia)
                            .addComponent(jLabel7))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblThanhTien))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInHD)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInHDActionPerformed
        // TODO add your handling code here:
        inHoaDon();
        this.dispose();
    }//GEN-LAST:event_btnInHDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    private void inHoaDon() {
//        btHeight = Double.valueOf(loaiVe.size());
//        bbHeight = Double.valueOf(tenMon.size());

        PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setPrintable((Printable) new BillPrintable(), getPageFormat(pj));
        try {
            //XDialog.alert(this, "Vui lòng tắt hoá đơn đang mở (nếu có) để in hoá đơn mới!");
            pj.print();
        } catch (PrinterException ex) {
            return;
        }
    }
   
    
     private void setFormHD() {
//         arrhd = dhdao.getDHbyMa(MaBan);
        //order = dhctdao.getDSOder(arrhd.getId());
        hoadon = service.getIDByMaHD(lblMa.getText());
        dsmon = serviceHdct.getDSHDCT(hoadon.getId());
         km = kmservice.getbyMaKM(lblGiamGia.getText());
        // JOptionPane.showMessageDialog(this, order.size());
        for (int i = 0; i < dsmon .size(); i++) {         
            int sl = dsmon .get(i).getSoLuong();
            String tenmon = dsmon .get(i).getTenMon();
            BigDecimal dongia  = new BigDecimal(dsmon .get(i).getDonGia()+""); 
            //BigDecimal tien = new BigDecimal(sl).multiply(dongia);
            tenMon.add(tenmon);
            soLuongMon.add(sl);
            donGiaMon.add(dongia);
           // thanhTienMon.add(tien);
        }
        }
     private PageFormat getPageFormat(PrinterJob pj) {

        PageFormat pf = pj.defaultPage();
        Paper paper = pf.getPaper();
        double bodyHeight = btHeight + bbHeight;
        double headerHeight = 5.0;
        double footerHeight = 8.0;
        double width = cm_to_pp(25);
        double height = cm_to_pp(headerHeight + bodyHeight + footerHeight);
        paper.setSize(width, height);
        paper.setImageableArea(0, 10, width, height - cm_to_pp(1));
        pf.setOrientation(PageFormat.PORTRAIT);
        pf.setPaper(paper);
        return pf;
    }
    private class BillPrintable implements Printable {
      
        @Override
        public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
          //  int r = tenMon.size();
            int result = NO_SUCH_PAGE;
            if (pageIndex == 0) {
                Graphics2D g2d = (Graphics2D) graphics;
                Graphics2D g2dtitle = (Graphics2D) graphics;
                Graphics2D g2dtt = (Graphics2D) graphics;
                g2d.translate((int) pageFormat.getImageableX(), (int) pageFormat.getImageableY());
                try {
                    int y = 20;
                    int yShift = 12;
                    int headerRectHeight = 15;
                 
                    ImageIcon logo = new ImageIcon("C:\\DuAn\\DuAn1\\src\\main\\java\\Images\\waiter.png");
                    g2d.drawImage(logo.getImage(), 162, 20, 100, 70, rootPane);
                    y += yShift + 90;
                    g2dtitle.setFont(new Font("Monospaced", Font.BOLD, 18));
                    g2dtitle.drawString(" PHIẾU THANH TOÁN ", 115, y);
                    y += yShift;
                    g2d.setFont(new Font("Monospaced", Font.PLAIN, 9));
                    g2d.drawString("    ----------------------------------------------------", 48, y);
                    y += headerRectHeight;
                    g2d.setFont(new Font("Monospaced", Font.BOLD, 9));
                    g2d.drawString("Bàn số:", 70, y);
                    g2d.drawString(lblBan.getText(), 155, y);
                    y += yShift;
                    g2d.setFont(new Font("Monospaced", Font.PLAIN, 9));
                    g2d.drawString("Giờ vào:", 70, y);
                    g2d.drawString(lblNgayTao.getText(), 155, y);
                   
                   
                 
                    y += yShift + 10;
                    g2d.drawString("Món", 70, y);
                    g2d.drawString("SL", 175, y);
                    g2d.drawString("Đ.Giá", 220, y);
                   // g2d.drawString("T.Tiền", 290, y);
                    y += yShift - 2;
                    g2d.drawString("    ----------------------------------------------------", 48, y);
//                    arrhd = dhdao.getDHbyMa(MaBan);
//                    arrhd = dhdao.getDHbyMa(MaBan);
                    //order = dhctdao.getDSOder(arrhd.getId());
                    hoadon = service.getIDByMaHD(lblMa.getText());
                    dsmon = serviceHdct.getDSHDCT(hoadon.getId());
                    int khuyenmai = km.getId();
                    double tong = Double.parseDouble(lblThanhTien.getText());                   
                    double tiengiam = tong*khuyenmai*0.01;
                    double thanhtien = tong - tiengiam;
                    y += headerRectHeight;
                     for (int i = 0; i < dsmon.size(); i++) {
                       g2d.drawString(tenMon.get(i), 70, y);
                        g2d.drawString(String.valueOf(soLuongMon.get(i)), 175, y);
                        g2d.drawString((String.valueOf(donGiaMon.get(i))), 220, y);
                       // g2d.drawString((String.valueOf(thanhTienMon.get(i))), 290, y);
                        y += yShift;
                    }
                   
                    g2d.drawString("    ----------------------------------------------------", 48, y);
                    y += yShift;
                    g2dtt.setFont(new Font("Monospaced", Font.BOLD, 9));
                     y += yShift + 2;
                    g2dtt.drawString("Mã HĐ:", 70, y);
                    g2dtt.drawString(lblMa.getText() , 290, y);
                    y += yShift + 2;
                     g2dtt.drawString("Tổng tiền:", 70, y);
                      g2dtt.drawString(String.valueOf(lblThanhTien.getText())+" VNĐ", 290, y);
                    y += yShift + 2;
                    g2dtt.drawString("Giảm giá:", 70, y);
                    g2dtt.drawString(lblGiamGia.getText()+"-"+km.getPhanTram()+"%" , 290, y);
                    g2dtt.setFont(new Font("Monospaced", Font.PLAIN, 9));
                
                    g2dtt.setFont(new Font("Monospaced", Font.BOLD, 9));
                    y += yShift + 2;
                    g2dtt.drawString("Thành tiền:", 70, y);
                     g2dtt.drawString(String.valueOf(thanhtien)+" VNĐ", 290, y);
                   
                    y += yShift;
                    g2d.setFont(new Font("Monospaced", Font.PLAIN, 9));
                    g2d.drawString("    ----------------------------------------------------", 48, y);
                    y += yShift;
                    g2d.drawString("   CHÚC QUÝ KHÁCH VUI VẺ, HẸN GẶP LẠI ", 95, y);
                    y += yShift;
                    g2d.drawString("   ********************************************", 50, y);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                result = PAGE_EXISTS;
            }
            return result;
     }
        }
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChiTietHoaDonJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChiTietHoaDonJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChiTietHoaDonJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChiTietHoaDonJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ChiTietHoaDonJdialog dialog = new ChiTietHoaDonJdialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInHD;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBan;
    private javax.swing.JLabel lblGiamGia;
    private javax.swing.JLabel lblKhuVuc;
    private javax.swing.JLabel lblMa;
    private javax.swing.JLabel lblNgayTao;
    private javax.swing.JLabel lblThanhTien;
    private javax.swing.JTable tblSanPham;
    // End of variables declaration//GEN-END:variables
}
